Repository TransparentHealth/smh_app, pull requests merged in 2019-10, with the labels that each got.

#234 Fix Diagnoses display
  apps/member/views.py
Labels: bug

#235 LOTS of DEBUG logging
  apps/member/utils.py
  apps/member/views.py
  manage.py
Labels: bug

#238 Pipeline cleanup
  apps/users/pipeline/oidc.py
  apps/users/utils.py
  apps/verifymyidentity/backends/authentication.py
  apps/verifymyidentity/backends/backends.py
Labels: bug, infrastructure

#239 Auth pipeline fixes
  apps/org/forms.py
  apps/org/tests/test_views.py
  apps/org/views.py
  apps/users/admin.py
  apps/users/models.py
  apps/users/tests/test_models.py
  apps/verifymyidentity/pipeline/get_user_id.py
  apps/verifymyidentity/pipeline/organizations.py
  smh_app/settings.py
Labels: bug, enhancement

#242 Fix create member bug
  .gitignore
  apps/notifications/models.py
  apps/notifications/views.py
  apps/org/models.py
  apps/org/tests/test_views.py
  apps/org/views.py
  apps/users/migrations/0009_auto_20191016_2010.py
Labels: bug

#246 Fix avatar display for agent
  apps/member/templates/member_sidebar.html
Labels: bug

#248 Ui updates security
  apps/member/templates/member/dashboard.html
  apps/users/templates/users/homepage.html
  requirements.txt
  templates/header.html
  templates/registration/login.html
Labels: enhancement
